// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibmctcnuekqqhikdlumx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibWN0Y251ZWtxcWhpa2RsdW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzgzODQsImV4cCI6MjA2NDYxNDM4NH0.VkMcLE5w7480Smi1Yn4euZJnC-DDbwnAndaM-vRbZEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);